# Generated by Django 4.0.4 on 2022-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.CharField(default='요리', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_fileName',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_manufacturer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_unit',
            field=models.IntegerField(default=100, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_unitPrice',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
